# from selenium import webdriver
# driver = webdriver.Chrome("C:\chromedriver.exe")
# driver.maximize_window()
# driver.get("http://practice.automationtesting.in/")
# driver.execute_script("window.scrollBy(0, 600);")
# selenium_btn =driver.find_element_by_tag_name('[href="http://practice.automationtesting.in/product/selenium-ruby/"]').click()
# review_btn = driver.find_element_by_tag_name('[href="#tab-reviews"]').click()
# star_5 = driver.find_element_by_class_name("star-5").click()
# comment = driver.find_element_by_id("comment")
# comment.click()
# comment.send_keys("Nice book!")
# name_btn = driver.find_element_by_id("author")
# name_btn.click()
# name_btn.send_keys("John Connor")
# email_btn = driver.find_element_by_id("email")
# email_btn.click()
# email_btn.send_keys("JohnConnor@terminator.com")
# submit_btn =driver.find_element_by_id("submit").click()
# driver.quit()

